[tox]
envlist = py312
skipsdist = True

[testenv]
runner = uv-venv-lock-runner
package = uv-editable
dependency_groups =
    test
commands =
    coverage run -m pytest
    coverage xml

[coverage:run]
relative_files = True
source = src/
branch = True
